In [1]:
# Добавление библиотек

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Загружаем и смотрим тренировочные данные

train_data = pd.read_csv(r"C:\Users\1\Desktop\Workplace\Рабочее пространство\Степик\Степик.Машинное обучение\Датасеты\ssz_data_manual\ssz_data\train.csv")
train_data.head()


id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
0  58036  18387       2     175    75.0    110     70            1     1   
1  88981  23328       2     155    66.0    140     90            1     1   
2  74325  17602       2     168    73.0    120     80            2     1   
3  16519  23432       2     183    95.0    140     90            1     1   
4  28981  23162       1     156    62.0    150     80            1     1   

   smoke  alco  active  cardio  
0      0     0       1       1  
1      1     1       0       0  
2      0     0       1       0  
3      0     0       0       1  
4      0     0       1       1

In [3]:
# Загружаем и смотрим тестовые данные

test_data = pd.read_csv(r"C:\Users\1\Desktop\Workplace\Рабочее пространство\Степик\Степик.Машинное обучение\Датасеты\ssz_data_manual\ssz_data\test.csv")
test_data.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
0  36043  17646       2     165    65.0    120     80            1     1   
1  44455  20418       1     161    77.0    120     70            1     1   
2  61323  20347       1     165    88.0    120     80            2     2   
3  27780  18086       2     170    91.0    120     80            3     3   
4  54273  21791       1     158    67.0    130     80            1     1   

   smoke  alco  active  cardio  
0      0     0       0       1  
1      0     0       1       1  
2      0     0       1       1  
3      0     0       1       1  
4      0     0       1       1

In [4]:
# Проверяем на наличие NaN и строковых данных

train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58000 entries, 0 to 57999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           58000 non-null  int64  
 1   age          58000 non-null  int64  
 2   gender       58000 non-null  int64  
 3   height       58000 non-null  int64  
 4   weight       58000 non-null  float64
 5   ap_hi        58000 non-null  int64  
 6   ap_lo        58000 non-null  int64  
 7   cholesterol  58000 non-null  int64  
 8   gluc         58000 non-null  int64  
 9   smoke        58000 non-null  int64  
 10  alco         58000 non-null  int64  
 11  active       58000 non-null  int64  
 12  cardio       58000 non-null  int64  
dtypes: float64(1), int64(12)
memory usage: 5.8 MB


In [5]:
# Делим тренировочные и тестовые данные на признаки и целевую переменную.

X_train = train_data.drop(columns = ['cardio'])  # Признаки (все, кроме cardio )
y_train = train_data['cardio']  # Целевая переменная

X_test = test_data.drop(columns = ['cardio'])
y_test = test_data['cardio']

In [6]:
# Здесь должна быть предобработка данных 

In [14]:
# Обучим модель при помощи логистической регрессии

from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression() 

logreg.fit(X_train, y_train)



C:\Users\1\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
# "Попросим" ответы лог.регрессии. Подаются только признаки

y_predicted_logreg = logreg.predict(X_test)
y_predicted_logreg

array([0, 1, 1, ..., 0, 1, 1], dtype=int64)

In [17]:
# Сравним истинные ответы и ответы, полученные путём машинного обучения

print(y_predicted_logreg[:10])  # Машинка
print(np.array(y_test)[:10])  # Истина

[0 1 1 0 1 1 0 0 1 0]
[1 1 1 1 1 1 0 0 0 0]


In [72]:
# Обучим модель при помощи случайного леса 

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=10000, max_depth=10)  # Количество деревьев 20, глубина каждого дерева - 10

rf.fit(X_train, y_train)



RandomForestClassifier(max_depth=10, n_estimators=10000)

In [73]:
y_predicted_rf = rf.predict(X_test)
y_predicted_rf

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [70]:
print(y_predicted_rf[:10])
print(np.array(y_test)[:10])

[0 0 0 1 1 1 0 0 1 0]
[1 1 1 1 1 1 0 0 0 0]


In [71]:
# Посчитаем метрики качества обоих алгоритмов при помощи accuracy. accuracy - доля правильно угаданных ответов

from sklearn.metrics import accuracy_score

print(accuracy_score(y_predicted_logreg, y_test))
print(accuracy_score(y_predicted_rf, y_test))

# рандомный лес справился лучше по accuracy

0.6921666666666667
0.7340833333333333


In [67]:
# Посчитаем метрики качества обоих алгоримтом при помощи F1. F1 - метрика бинарной классификации.

from sklearn.metrics import f1_score
print(f1_score(y_predicted_logreg, y_test))
print(f1_score(y_predicted_rf, y_test))

0.6835703272228885
0.7150476523563871
