In [6]:
%%time

arr = []
n = 10**7

for i in range(n):
    arr.append(i*5)
    
# Смотрим на время работы программы

Wall time: 1.42 s


In [11]:
%%time

def summ(a):
    ans = 0
    
    for i in a:
        ans += 1 
    return ans

arr = range(10**7)
print(summ(arr))

# Смотрим на время работы программы

10000000
True
Wall time: 489 ms


In [15]:
import numpy as np

a = [1,2,3]
b = np.array(a, dtype='float64')
print(type(b), type(a))

<class 'numpy.ndarray'> <class 'list'>


In [16]:
# Если разные типы данных, то неявный каст сведёт их к одному

a = [1,2,'a']
b = np.array(a)

print('Для list:', type(a[0]), '\nДля np.array:', type(b[0]))

Для list: <class 'int'> 
Для np.array: <class 'numpy.str_'>


In [18]:
d = np.array([1,2,3])
print(d)
print(type(d))

[1 2 3]
<class 'numpy.ndarray'>


In [19]:
set(dir(b)) - (set(dir(object)))

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delitem__',
 '__divmod__',
 '__float__',
 '__floordiv__',
 '__getitem__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__len__',
 '__lshift__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__neg__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setitem__',
 '__setstate__',
 '__sub__',


In [23]:
arr = np.array([1,2,3,4,5], dtype='int32')
arr.nbytes

20

In [24]:
# Если не знаете нужную функцию, но понимаете, чего хотите, тогда можно
# воспользоваться поиском в документации

np.lookfor('Mean value of array')

Search results for 'mean value of array'
----------------------------------------
numpy.ma.mean
    Returns the average of the array elements along given axis.
numpy.mean
    Compute the arithmetic mean along the specified axis.
numpy.nanmean
    Compute the arithmetic mean along the specified axis, ignoring NaNs.
numpy.put
    Replaces specified elements of an array with given values.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.digitize
    Return the indices of the bins to which each value in input array belongs.
numpy.unpackbits
    Unpacks elements of a uint8 array into a binary-valued output array.
numpy.nanquantile
    Compute the qth quantile of the data along the specified axis,
numpy.ma.dot
    Return the dot product of two arrays.
numpy.count_nonzero
    Counts the number of non-zero values in the array ``a``.
numpy.ma.fix_invalid
    Return input with invalid data masked and replaced by a fill value.
numpy.matrix.partition
    R

In [25]:
?np.ma.mean # вопросик перед функцией открывает страничку документации

In [26]:
np.con*? # возможные варианты продолжения функции (concatenate,conj,convole...)

In [27]:
# Посмотрим на количественные характеристики ndarray

arr = np.array([
    [[1,2,3,4],
    [2,3,4,3],
    [1,1,1,1]],
                
    [[1,2,3,4],
    [2,3,4,3],
    [1,1,1,1]]
])

print(arr)

[[[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]

 [[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]]


In [31]:
print(" len: ", len(arr), '-- количество элементов первой оси.\n',
     'size:', arr.size, '-- всегда элементов в матрице.\n',
     'ndim:', arr.ndim, '-- размерность матрицы.\n',
     'shape:', arr.shape, '-- количество элементов по каждой оси.') 
#shape (количество матриц х высота матрицы х ширина матрицы)

 len:  2 -- количество элементов первой оси.
 size: 24 -- всегда элементов в матрице.
 ndim: 3 -- размерность матрицы.
 shape: (2, 3, 4) -- количество элементов по каждой оси.


In [35]:
arr_Q_1 = np.array([2,3,5,7],dtype='int32')
print(type(arr_Q_1))
print(arr_Q_1.ndim)
print(arr_Q_1.nbytes)

<class 'numpy.ndarray'>
1
16


## Создание массивов

In [37]:
a = np.zeros(7) # массив из N-нулей (7 в данном случае)
b = np.ones(7, dtype=np.int16) # массив из N единиц
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1]


In [40]:
c = np.zeros(7) # обычная работа zeros
c

[0. 0. 0. 0. 0. 0. 0.]


In [41]:
c = np.zeros_like(b) # создаёт массив нулей аналогичный по размеру и типу b
c

array([0, 0, 0, 0, 0, 0, 0], dtype=int16)

#### функция *np.arrange* подобна range, но позволяет работать с float

In [46]:
a = np.arange(1,16,4) #int
b = np.arange(5.,21,2) #float
print(a)
print(b)

[ 1  5  9 13]
[ 5.  7.  9. 11. 13. 15. 17. 19.]


#### Последовательность чисел с постоянным шагом можно также создат функцией *linspace*. Начало и конец диапазона включаются.Последний аргумент -- количество точек
#### lin - линейное, space - пространство. Название функции ознчает, что она задает точки на линейном пространстве

In [50]:
a = np.linspace(1,15,2) 
b = np.linspace(5,12,10) 
print(a)
print(b)

[ 1. 15.]
[ 5.          5.77777778  6.55555556  7.33333333  8.11111111  8.88888889
  9.66666667 10.44444444 11.22222222 12.        ]


In [51]:
#последовательность чисел от 10 до 32 с пост.шагом,
#чтобы длина последовательности была равна 12
arr_Q_2 = np.linspace(10,32,12)
print(arr_Q_2)
print('Шаг равен: {}'.format(arr_Q_2[2] - arr_Q_2[1]))

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
Шаг равен: 2.0


#### аналог для логарифмического пространства logspace

In [53]:
b = np.logspace(0,3,12)
b

array([   1.        ,    1.87381742,    3.51119173,    6.57933225,
         12.32846739,   23.101297  ,   43.28761281,   81.11308308,
        151.9911083 ,  284.80358684,  533.66992312, 1000.        ])

# Операции над одномерными массивами

In [54]:
a = np.linspace(3,33,11)
b = np.linspace(-2,-22,11)
print(a)
print(b)

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]


In [55]:
# для проведения операций массивы должны быть одного размера
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
[  -6.  -24.  -54.  -96. -150. -216. -294. -384. -486. -600. -726.]
[-1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5]


#### Один из операндов может быть скаляром, а не массивом

In [56]:
print(5 * a)
print(10 + b)

[ 15.  30.  45.  60.  75.  90. 105. 120. 135. 150. 165.]
[  8.   6.   4.   2.   0.  -2.  -4.  -6.  -8. -10. -12.]


In [57]:
print((a+b)**2)
print(2**(a+b))

[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01 6.400e+01 1.280e+02
 2.560e+02 5.120e+02 1.024e+03 2.048e+03]


In [58]:
# если типы элементов разные, то идёт каст к большему

print(a + np.arange(11,dtype='int16'))
print(type(a[0]))

[ 3.  7. 11. 15. 19. 23. 27. 31. 35. 39. 43.]
<class 'numpy.float64'>


#### В numpy есть элементарные функции, которые тоже применяются к массивам поэлементно
#### Они называются универсальными функциями (ufunc) - cos,sin, lg, exp

In [59]:
np.cos(a)

array([-0.9899925 ,  0.96017029, -0.91113026,  0.84385396, -0.75968791,
        0.66031671, -0.54772926,  0.42417901, -0.29213881,  0.15425145,
       -0.01327675])

In [60]:
np.log(b) # везде nan, т.к. каждый элемент массива b < 0

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [63]:
# можно поэлементно  выполнять логические операции 

print(a>b)
print(a==b)
print(a >= 10)

[ True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False]
[False False False  True  True  True  True  True  True  True  True]


#### Кванторы всеобщности и существования

In [76]:
c = np.arange(0.,20) #float64


print('',
      np.any(c == 0),'\n',
      np.all(c)) # эквивалентно c != 0. False, т.к. первый элемент массива - 0
print(c)

 True 
 False
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


#### Inplace операции. Возможны для операндов одинакового типа

In [80]:
c += np.sin(4)
c

array([-2.27040749, -1.27040749, -0.27040749,  0.72959251,  1.72959251,
        2.72959251,  3.72959251,  4.72959251,  5.72959251,  6.72959251,
        7.72959251,  8.72959251,  9.72959251, 10.72959251, 11.72959251,
       12.72959251, 13.72959251, 14.72959251, 15.72959251, 16.72959251])

# Полезные функции

#### np.e,     # получение экспоненты
#### np.pi,     # получение числа pi
#### array.sort(),  # сортировка массива array
#### np.sort(a),  # сортировка массива a без inplace (сам массив не изменится)
#### np.hstack((a,b,c)), # объединение трёх массивов в один
#### np.hsplit(a, [3,5,6]), # разъединение (разделение) одного массива на 4
#### np.delete(a,[2,4,1]), # удаление элементов массива по индексу (не inplace)
#### np.insert(a, 2, [-1,-1]), # Добавление значений в массиве по индексу (ряд значений. Не inplace)
#### np.append(a, [2.2,2.1]), # Добавление значений в конец массива
#### a[::-1], # "переворот" массива
#### a.copy(), # создание копии массива а
#### a[[5,3,1]], # создание массива по индексам 5,3,1 (передается массив индексов)
#### np.linspace(1,5,10), # массив из 10 точек от 1 до 5
#### np.all('conditions'), # квантор всеобщности
#### np.any('conditions'), # квантор существования
#### np.cos(a), # поэлементный косинус от массива а
#### np.sin(a), # поэлементный синус от массива а
#### a.ravel() # многомерный массив в одномерный
#### a.eye(N) # квадратная матрица размера N с 1 на главной диагонали и 0 на других
#### a.dot(b) # матричное умножение (или (a @ b))
#### np.trace(a) # сумма элементов главной диагонали
#### np.diag(array) # Создание квадратной матрицы с элементами массива array на главной диагонали
#### np.zeros(N) # матрица 0. N может быть int и turple
#### np.ones(N) # матрица 1. N может быть int и turple
#### np.linalg.det(a) # детерминант матрицы а

In [82]:
x1,x2,x3,x4 = np.hsplit(a, [3,5,6])
print(a)
print(x1)
print(x2)
print(x3)
print(x4)

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[3. 6. 9.]
[12. 15.]
[18.]
[21. 24. 27. 30. 33.]


In [83]:
b = a[0:6]  # копия не создается. Работа происходит в тех же ячейках памяти, где и хранится сам массив а
b[1] = -1000
print(a)

[    3. -1000.     9.    12.    15.    18.    21.    24.    27.    30.
    33.]


In [90]:
arr_Q_3 = np.linspace(-4 *np.pi, 4*np.pi, 100)
arr_Q_3_answer = (np.cos(arr_Q_3))**2 + (np.sin(arr_Q_3))**2
print(np.all(arr_Q_3_answer.round() == 1))

True


## Двумерные массивы

In [91]:
dbl = np.array([
    [1,2],
    [3,4]
])

dbl

array([[1, 2],
       [3, 4]])

In [92]:
dbl.ndim, dbl.shape, len(dbl), dbl.size

(2, (2, 2), 2, 4)

In [96]:
# Обращение по индексу
dbl[1][1]
dbl[1,1]

4

#### Атрибуты shape можно присвоить новое значение -- кортеж размеров по всем координатам. Получится новый заголовой массива; его данные не изменятся

In [98]:
b_dbl = np.arange(0,20) # один массив 20
b_dbl.shape = (2,10) # 2 массива по 10
print(b_dbl)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [99]:
b_dbl.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [101]:
x = np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [103]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [105]:
x = np.diag(np.array([4,6,1,2]))
x

array([[4, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 2]])

In [113]:
arr_Q_4 = -1 * np.eye(8, dtype='int32')[::-1] + np.diag(np.linspace(3,3*8,8, dtype='int32'))
arr_Q_4

array([[ 3,  0,  0,  0,  0,  0,  0, -1],
       [ 0,  6,  0,  0,  0,  0, -1,  0],
       [ 0,  0,  9,  0,  0, -1,  0,  0],
       [ 0,  0,  0, 12, -1,  0,  0,  0],
       [ 0,  0,  0, -1, 15,  0,  0,  0],
       [ 0,  0, -1,  0,  0, 18,  0,  0],
       [ 0, -1,  0,  0,  0,  0, 21,  0],
       [-1,  0,  0,  0,  0,  0,  0, 24]])

In [115]:
# Умножение матриц

a = 5 * np.ones((5,5))
b = np.eye(5)+1
print(a,'\n')
print(b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] 

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [116]:
print(a*b,'\n') # поэлементное умножение
print(a @ b, '\n') # матричное умножение
print(a.dot(b))

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


In [117]:
# Двумерные массивы, зависящие только от одного индекса Xij = Uj, Yij = Vj
# Для графиков.

u = np.linspace(1,2,2)
v = np.linspace(4,8,3)
print(u)
print(v)

[1. 2.]
[4. 6. 8.]


In [118]:
x, y = np.meshgrid(u,v)
print(x, '\n')
print(y)

[[1. 2.]
 [1. 2.]
 [1. 2.]] 

[[4. 4.]
 [6. 6.]
 [8. 8.]]


In [119]:
x.reshape(6) # как shape, только наоборот

array([1., 2., 1., 2., 1., 2.])

In [122]:
arr_Q_5 = np.ones(100, dtype=bool)
arr_Q_5[:2] = False

In [123]:
N_max = int(np.sqrt(len(arr_Q_5)))

for i in range(2, N_max):
    arr_Q_5 [2*i::i] = False #Начинам с 2i с шагом i
arr_Q_5

array([False, False,  True,  True, False,  True, False,  True, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
       False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
       False])

### Маски

In [125]:
a = np.arange(20)
print(a%3 == 0, '\n')
print(a[a%3 == 0]) # - по маске взяли значение

[ True False False  True False False  True False False  True False False
  True False False  True False False  True False] 

[ 0  3  6  9 12 15 18]


### След (trace) - сумма диагональных элементов

In [128]:
b = np.diag(a[a >= 10])
b
print(np.trace(b))

145


# Тензоры (многомерные массивы)

In [131]:
X = np.arange(64).reshape(8,2,4)
X

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55]],

       [[56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [132]:
X.shape, len(X), X.size, X.ndim

((8, 2, 4), 8, 64, 3)

In [134]:
np.sum(X) - сумма всех элементов массива

2016

In [136]:
print(np.sum(X, axis=0),'\n') # матрица 2х4 без нулевой оси
print(np.sum(X, axis=1),'\n') # матрица 8х4 без первой оси
print(np.sum(X, axis=2)) # матрица 8х2 без второй оси

[[224 232 240 248]
 [256 264 272 280]] 

[[  4   6   8  10]
 [ 20  22  24  26]
 [ 36  38  40  42]
 [ 52  54  56  58]
 [ 68  70  72  74]
 [ 84  86  88  90]
 [100 102 104 106]
 [116 118 120 122]] 

[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]
 [134 150]
 [166 182]
 [198 214]
 [230 246]]


# Линейная алгебра

In [142]:
a = np.array([[2,1],[3,3]])
a

array([[2, 1],
       [3, 3]])

In [143]:
# определитель
np.linalg.det(a)

2.9999999999999996

In [144]:
# обратная матрица
b = np.linalg.inv(a)
b

array([[ 1.        , -0.33333333],
       [-1.        ,  0.66666667]])

In [145]:
print(a.dot(b))
print(b.dot(a))

[[ 1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00]]
[[ 1.0000000e+00  0.0000000e+00]
 [-4.4408921e-16  1.0000000e+00]]
